# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 01:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '__first__'),
    ]



    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('city', models.CharField(blank=True, max_length=20)),
                ('cell_number', models.CharField(blank=True, max_length=15)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=40)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('meal_restrictions', models.CharField(blank=True, max_length=200)),
                ('other_restrictions', models.CharField(blank=True, max_length=100)),
                ('arrival_day', models.IntegerField(blank=True, null=True, choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('departure_day', models.IntegerField(blank=True, null=True, choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('has_ticket', models.BooleanField(default=False)),
                ('looking_for_ticket', models.BooleanField(default=True)),
                ('camping_this_year', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BicycleMutationInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('units', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_photo', models.ImageField(blank=True, null=True, upload_to=b'bike_images')),
                ('bike_name', models.CharField(max_length=30)),
                ('bike_frame_size_inches', models.IntegerField()),
                ('owners_last_year_on_playa', models.IntegerField(default=1)),
                ('stored_in_truck', models.BooleanField(default=True)),
                ('needs_repairs', models.BooleanField(default=False)),
                ('repair_needed', models.CharField(blank=True, choices=[(b'nothing', b'nothing'), (b'needs_wheel_or_hub', b'needs_wheel_or_hub'), (b'tube', b'tube'), (b'brake adjustment', b'brake adjustment'), (b'seat', b'seat'), (b'pedal', b'pedal'), (b'tire', b'tire'), (b'new_chain', b'new_chain'), (b'derailer', b'derailer'), (b'brake repair', b'brake repair'), (b'head tightening', b'head tightening'), (b'cable repair or lube', b'cable repair or lube'), (b'other', b'other')], max_length=30, null=True)),
                ('in_bike_pool_this_year', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=30, null=True)),
                ('bike_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BikeMutationSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[(b'Morning', b'Morning'), (b'Afternoon', b'Afternoon')], max_length=25)),
                ('day', models.IntegerField(choices=[(1, b'Monday'), (2, b'Tuesday'), (3, b'Wednesday'), (4, b'Thursday'), (5, b'Friday')])),
                ('assigned', models.BooleanField(default=False)),
                ('camper', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=20)),
                ('quantity', models.IntegerField()),
                ('needs_repairs', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', models.BooleanField(default=False)),
                ('day', models.IntegerField(choices=[(0, b'Sunday'), (1, b'Monday'), (2, b'Tuesday'), (3, b'Wednesday'), (4, b'Thursday'), (5, b'Friday'), (6, b'Saturday')])),
                ('meal', models.CharField(choices=[(b'Breakfast', b'Breakfast'), (b'Dinner', b'Dinner')], max_length=10)),
                ('shift', models.CharField(choices=[(b'Chef', b'Chef'), (b'Sous-Chef', b'Sous_Chef'), (b'KP', b'KP')], default=b'KP', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('camper', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeping_arrangement', models.CharField(choices=[(b'bringing_own_tent', b'bringing own tent'), (b"sharing someone else's tent", b"sharing someone else's tent"), (b'using camp yurt', b'using_camp_yurt'), (b'sharing rv', b'sharing_rv'), (b'other', b'other')], max_length=25)),
                ('number_of_people_tent_sleeps', models.IntegerField()),
                ('sleeping_under_ubertent', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_driver_in_your_party', models.BooleanField(default=False)),
                ('model_of_car', models.CharField(blank=True, default=None, max_length=25)),
                ('make_of_car', models.CharField(blank=True, default=None, max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='mealshift',
            unique_together=set([('day', 'meal', 'shift')]),
        ),
    ]
