# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 03:58
from __future__ import unicode_literals

from django.db import migrations

def nuke_data(apps, schema_editor):
    BMS = apps.get_model('camp', 'bikemutationschedule')
    BMS.objects.all().delete()
    User = apps.get_model('camp', 'User')
    User.objects.all().delete()

def noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_chef_signup'),
    ]

    operations = [
        migrations.RunPython(nuke_data, noop)
    ]
