# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 03:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0003_nuke_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikemutationschedule',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='bikemutationschedule',
            name='day',
        ),
        migrations.RemoveField(
            model_name='user',
            name='arrival_day',
        ),
        migrations.RemoveField(
            model_name='user',
            name='departure_day',
        ),
        migrations.AddField(
            model_name='bikemutationschedule',
            name='date',
            field=models.DateField(default=datetime.datetime(2000, 1, 1, 0, 0, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bikemutationschedule',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='camp.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='arrival_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='departure_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
