# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0004_date_and_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealshift',
            name='role',
            field=models.CharField(choices=[('courier', 'Courier'), ('chef', 'Chef'), ('sous-chef', 'Sous Chef'), ('kp', 'KP')], default='kp', max_length=10),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='sleeping_arrangement',
            field=models.CharField(choices=[('bringing_own_tent', 'bringing own tent'), ("sharing someone else's tent", "sharing someone else's tent"), ('using camp yurt', 'using camp yurt'), ('sharing rv', 'sharing rv'), ('other', 'other')], max_length=25),
        ),
    ]
