# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-30 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0006_add_vehicle_and_shelter_dimensions_and_playa_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='meal_restrictions',
        ),
        migrations.AddField(
            model_name='user',
            name='meal_restrictions',
            field=models.ManyToManyField(related_name='campers', to='camp.MealRestriction'),
        ),
    ]
