# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-30 06:16
from __future__ import unicode_literals

from django.db import migrations


def populate_restrictions(apps, schema_editor):
    MealRestriction = apps.get_model('camp', 'mealrestriction')

    restrictions = [
        'Vegetarian', 'Vegan', 'Dairy', 'Lactose', 'Artificial sweetener', 'Cilantro',
        'Mushroom', 'Shellfish', 'Olives', 'Capers', 'Gluten', 'Nightshade']
    for restriction in restrictions:
        MealRestriction.objects.create(name=restriction)

class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0007_rework_meal_restriction'),
    ]

    operations = [
        migrations.RunPython(populate_restrictions, migrations.RunPython.noop)
    ]
