# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-31 19:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0011_not_null_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='shelter_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provided_shelter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='number_of_people_tent_sleeps',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='sleeping_arrangement',
            field=models.CharField(choices=[('dunno', 'Not sure yet'), ('bringing', 'Bringing own tent'), ('car', 'Sleeping in own vehicle'), ('yurt', 'Using camp yurt'), ('sharing', "Sharing someone else's"), ('other', 'Other')], max_length=25),
        ),
    ]
