# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-02 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0015_add_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='number_of_people_tent_sleeps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
