# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-22 03:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from camp.shortcuts import get_current_event

def move_attendance(apps, schema_editor):
    User = apps.get_model('camp', 'user')
    UserAttendance = apps.get_model('camp', 'userattendance')
    Event = apps.get_model('camp', 'event')

    event = Event.objects.get()

    for user in User.objects.all():
        kwargs = {}
        for field in ['arrival_date', 'departure_date', 'date',
            'has_ticket', 'looking_for_ticket', 'camping_this_year']:
            kwargs[field] = getattr(user, field)

        UserAttendance.objects.create(user=user, event=event,
                **kwargs)


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0016_camp_shelter_sleeps_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('departure_date', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('has_ticket', models.BooleanField(default=False)),
                ('looking_for_ticket', models.BooleanField(default=True)),
                ('camping_this_year', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.Event')),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('last_name', 'first_name')},
        ),
        migrations.AddField(
            model_name='userattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userattendance',
            unique_together=set([('user', 'event')]),
        ),
        migrations.RunPython(move_attendance, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='camping_this_year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_ticket',
        ),
        migrations.RemoveField(
            model_name='user',
            name='looking_for_ticket',
        ),
        migrations.AlterField(
            model_name='meal',
            name='kind',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Dinner', 'Dinner'), ('Midnight', 'Midnight BBQ')], default='Dinner', max_length=10),
        ),
    ]
