# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-02 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0017_move_attendance'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='userattendance',
            name='paid_dues',
            field=models.BooleanField(default=False),
        ),
    ]
